services:
  - type: web
    name: html-screenshot-service
    env: node
    plan: free

    buildCommand: npm install && node install-chrome.js
    startCommand: npm start

    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
